; Hier werden deine persönlichen Daten gespeichert.
; Fülle die Daten aus, aber ändere nichts an der Struktur der Datei.
;
; Um T-Pak Token/User_id zu finden, gehe zu Entwickler-Tools (meist Ctrl/Cmd + Shift + I)
; und navigiere zum Tab Netzwerkanalyse. Mit dieser Analyse geöffnet, lade die Seite
; https://www.t-pak.ch/user/profile/admin (vielleicht musst du dich einloggen, dann ev. neuladen)
; Unter den Anfragen, finde unter Datei profile. Bei dieser Anfrage, finde den X-Auth-Token unter
; Anfragekopfzeilen. Bei dem Tab Antwort, scrolle etwas herum und finde "id" : "..." (eine 4-stellige Zahl)
; der X-Auth-Toke ist der token, die "id" ist die user_id (ohne Anführungszeichen)
;
; Dann, benenne die Datei zu User_Sensible_Information um (ohne _TEMPLATE).

[name]
name = Vorname Nachname

[garmin]
email = your@email.com
password = your!password

[t_pak]
user_id = 12345
token = your-t-pak-token

[settings]
default_trainingsgefaess = Regionalkader